### ISSUE TITLE
Feature Request: Add support for Cloud Run

### ISSUE THREAD

**Issue by ghost** [gcp-kit/gcpen#1]
@54m 
Would it be possible to add support for Cloud Run environment variables ?
https://cloud.google.com/run/docs/container-contract#env-vars

**Comment by 54m** [comment]
@tg-kozaki 
waiting for your contribution 😄

**Comment by ghost** [comment]
@54m 
Cloud you grant permission to write(push) ?

**Comment by 54m** [comment]
@tg-kozaki 
invited you to the organization(gcp-kit). plz check it.

**Comment by 54m** [comment]
or fork & pr

**Comment by ghost** [comment]
Thank you. I created PR. plz review this in your free time.

https://github.com/gcp-kit/gcpen/pull/2
